### ISSUE TITLE
ALS: Internal Error, Q is NaN.

### ISSUE THREAD

**Issue by StuntsPT** [cayek/TESS3#2]
This is more of a question than an error, but here it is:
When I run TESS3 on my dataset, I get the following output:
```
Read genotype file /home/francisco/Desktop/sequenom/TESS3/qsuber/Qsuber_sequenom_ok.geno:		OK.

Write W matrix into file /home/francisco/Desktop/sequenom/TESS3/qsuber/Qsuber_sequenom_ok.W:		OK.
Write L matrix into file /home/francisco/Desktop/sequenom/TESS3/qsuber/Qsuber_sequenom_ok.L:		OK.
Normalized beta parameter : inf

Main algorithm:
	[                                                                           ]
	[ALS: Internal Error, Q is NaN.
```

I do have some "9"'s in my dataset, but not that many. I do not see any "9"'s in the example files.

Any help is greatly appreciated.

Update: Replacing the "9"'s with "0"'s in my dataset does not resolve the error, so I guess it's not a missing data issue.

**Comment by joqb** [comment]
Same error here!
Any feedback?

**Comment by cayek** [comment]
We are working on a R package of the method TESS3 here : https://github.com/BioShock38/TESS3_encho_sen

The method is the same but several bugs have been fixed. The development version is almost ready for release. 

This R package will be soon released and the repository cayek/TESS3 will not be supported.

I advice you to use the new R package and post an issue if not fixed.

**Comment by StuntsPT** [comment]
Will do, thanks.
